FROM tensorflow/tensorflow:1.6.0-gpu-py3


RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get -y install python3.6

RUN pip install --upgrade pip
RUN pip install sagemaker-containers
